[Enahnce] Frontend dotfiles 추가
koreacreditdata/guides pull request #2
Opened 2021-01-08 09:47 UTC by seonghyeonkimm

## Descriptions
* 이번에 맥북 세팅을 하면서 @spilist 의 gist를 참고해서 세팅을 진행했습니다.
* 세팅을 진행하는 동안에 오류가 났었던 부분과 조금 더 보충되면 좋겠다고 한 부분들을 추가해보았습니다.

## Contents
  * 권한 이슈가 발생하지 않도록 하기 위해서 README에서 root access 후에 script를 실행하도록 안내사항을 적어두었습니다.
  * `nvm install`할 시에 version을 kestrel의 node version과 동일하게 설치할 수 있도록 업데이트했습니다.
  * 직접 path나 username을 변경할 필요 없이 직접 input을 받아서 적어줄 수 있도록 업데이트했습니다.
  * dotfiles에서 제공하는 `.gitconfig`, `.vimrc`, `.zshrc`을 사용하고 싶은지 선택할 수 있도록 했습니다.
  * `(.zshrc를 사용할경우)` `.nvmrc`가 있는 폴더에 진입했을 때에 자동으로 `nvm use`를 실행하도록 `.zshrc`를 개선했습니다.
  * `(.zshrc를 사용할 경우)` `oh-my-zsh`과 `oh-my-zsh plugins` 몇개를 사용할 수 있도록 추가해보았습니다.

2021-01-10 14:50 UTC, spilist requested changes
저의 엉성한 init script를 훨씬 발전시켜주셨네요. 멋집니다. 👍

2021-01-10 14:50 UTC, spilist commented on dotfiles/frontend/README.md
> +* [Reference](https://medium.com/harrythegreat/oh-my-zsh-iterm2%EB%A1%9C-%ED%84%B0%EB%AF%B8%EB%84%90%EC%9D%84-%EB%8D%94-%EA%B0%95%EB%A0%A5%ED%95%98%EA%B2%8C-a105f2c01bec)
iterm color scheme은 개인 취향일듯 꼭 필요한지 모르겠네요. 데미안이 이걸 공통 설정으로 하면 좋겠다고 생각하신 이유가 무엇일까요?

2021-01-10 14:50 UTC, spilist commented on dotfiles/frontend/main.sh
> +read -n 1 -r -p "Do you want to copy .zshrc file [Y/n]:" need_zshrc
와 이거 좋네요! 👍

2021-01-10 14:50 UTC, spilist commented on dotfiles/frontend/public/.gitconfig
> +	email = <YOUR_EMAIL>
아마 첨부터 제 gist가 이렇게 되어있었던 것 같은데 indent는 한 스타일로 맞추는 게 좋겠네요.

2021-01-10 14:50 UTC, spilist commented on dotfiles/frontend/public/.gitconfig
> +	trustExitCode = true
sourcetree를 안 쓸수도 있어서 여기는 빼는 게 좋겠습니다.

2021-01-10 14:50 UTC, spilist commented on dotfiles/frontend/public/init.Brewfile
> +cask "sourcetree"
이건 제가 개인적으로 쓰는 것들이니 빼시죠 ㅎㅎ figma 앱도 굳이 필요없을듯해요. 써보니 있는게 오히려 불편한 느낌이네요.

2021-01-10 14:50 UTC, spilist commented on dotfiles/frontend/public/.gitconfig
> +  postBuffer = 524288000
```suggestion
  postBuffer = 524288000
  #proxy = http://internal-proxy.kcd.systems:3128
```

gits 넣을 땐 없었는데 이 proxy가 codecommit access에 필요한데, VPN 처음에 부여 안받았을 때는 프록시 타면 안되니까 주석처리해둔 상태로 추가하고 README에 관련 내용도 적어두면 좋을 것 같습니다.

2021-01-10 14:50 UTC, spilist commented on dotfiles/frontend/scripts/install.sh
> +  nvm install 10.18.1
이건 좀 고민되네요. 프론트엔드에서 kestrel만 쓰리라는 보장이 없고, kestrel2에서는 node 14 쓸거고, LTS 버전이 계속 바뀔 거라서..  그냥 `nvm install node`로 latest 버전을 설치하고, 필요한 버전은 각 엔지니어가 추가로 설치하는 건 어떨까요?

2021-01-10 23:44 UTC, woongy commented on dotfiles/frontend/public/.gitconfig
> +  postBuffer = 524288000
코드커밋 저장소 접근만 프록시를 타면 되어서, 저는 이렇게 설정했습니다:
```gitconfig
[http "https://git-codecommit.ap-northeast-2.amazonaws.com"]
  proxy = http://internal-proxy.kcd.systems:3128
```
이렇게 하면 처음부터 추가해두어도 될 것 같아요.

2021-01-11 00:49 UTC, spilist commented on dotfiles/frontend/public/.gitconfig
> +  postBuffer = 524288000
오 이런 방법이 있었군요!

2021-01-11 01:04 UTC, seonghyeonkimm commented on dotfiles/frontend/README.md
> +* [Reference](https://medium.com/harrythegreat/oh-my-zsh-iterm2%EB%A1%9C-%ED%84%B0%EB%AF%B8%EB%84%90%EC%9D%84-%EB%8D%94-%EA%B0%95%EB%A0%A5%ED%95%98%EA%B2%8C-a105f2c01bec)
초반에 세팅할 때에 참고용이라고 생각하고 추가했었어요! 말씀 듣고 생각해보니 공통적인 것만 담는 것이 좋을 거 같아서 말씀해주신 내용들 삭제처리했습니다 🙏

2021-01-11 01:04 UTC, seonghyeonkimm commented on dotfiles/frontend/public/.gitconfig
> +	email = <YOUR_EMAIL>
수정했습니다!

2021-01-11 01:05 UTC, seonghyeonkimm commented on dotfiles/frontend/public/.gitconfig
> +	trustExitCode = true
삭제했습니다!

2021-01-11 01:05 UTC, seonghyeonkimm commented on dotfiles/frontend/public/init.Brewfile
> +cask "sourcetree"
삭제했습니다!

2021-01-11 01:06 UTC, seonghyeonkimm commented on dotfiles/frontend/public/.gitconfig
> +  postBuffer = 524288000
@woongy 가 말씀해주신대로 업데이트했어요 🙏

2021-01-11 01:06 UTC, seonghyeonkimm commented on dotfiles/frontend/scripts/install.sh
> +  nvm install 10.18.1
말씀해주신대로 곧 kestrel2를 만들게 될거고 node version도 바뀔 수 있다는 걸 생각못했네요. 말씀해주신대로 최신 node 설치하도록 업데이트했습니다!

2021-01-11 04:53 UTC, spilist approved these changes
고생하셨습니다. :)

2021-01-11 04:54 UTC, spilist commented
@woongy 이거 머지 룰이 까다롭게 되어있고 + 제게 머지 권한이 없네요. 머지해주시겠어요?

2021-01-11 05:05 UTC, woongy commented
"가이드라인"은 여러 구성원의 합의가 필요하다고 생각해서 머지 권한을 까다롭게 설정했는데, 요건 좀 얘기가 다르네요 😅 
머지 룰 무시하실 수 있게 @spilist 어드민 권한 드렸습니다.

2021-01-11 05:09 UTC, merged