[22690] vscode 관련 세팅 가이드에 추가 및 readme.md 업데이트
koreacreditdata/guides pull request #4
Opened 2021-06-10 01:41 UTC by ong-ar

[Clubhouse](https://app.clubhouse.io/korea-credit-data/story/22690/prettier-merlin-feather)

### 작업 내역

- .vscode 설정파일 추가
- `settings.json` 참고사항 `README.md` 에 내용 추가

2021-06-10 06:02 UTC, seonghyeonkimm approved these changes

2021-06-11 06:11 UTC, J132134 requested changes

2021-06-11 06:11 UTC, J132134 commented on dotfiles/frontend/README.md
> +```
[P1] 이거는 feather 가 특수한 경우라, feather README.md 로 옮기는게 좋을 것 같아요!

2021-06-11 06:11 UTC, J132134 commented on dotfiles/frontend/public/.vscode/extensions.json
> +  "unwantedRecommendations": []
unwantedRecommendations 빈 array 도 포함되어 있어야 하나요?

2021-06-11 06:11 UTC, J132134 commented on dotfiles/frontend/public/.vscode/extensions.json
> +    "esbenp.prettier-vscode",
[P2] prettier-vscode 는 @koreacreditdata/eslint-config 에서 eslint plugin 으로 사용중이기 때문에 제거해도 될 것 같아요!

2021-06-15 01:13 UTC, ong-ar commented on dotfiles/frontend/public/.vscode/extensions.json
> +  "unwantedRecommendations": []
빼도 관계는 없을 것 같습니다.
`template` 을 그대로 가져온거라 따로 빼지는 않았습니다.

2021-06-15 01:33 UTC, ong-ar commented on dotfiles/frontend/README.md
> +```
guide 라는 목적에서 만들어진 것 같아서 예외 케이스에 대한 것이 있어야한다고 생각해서 넣었습니다.

디폴트 값만 필요하다고 판단하시는 것 같아 제거했습니다.

2021-06-15 01:33 UTC, ong-ar commented on dotfiles/frontend/public/.vscode/extensions.json
> +    "esbenp.prettier-vscode",
수정했습니다.

2021-06-15 03:57 UTC, merged